### ISSUE TITLE
erasing data sets!

### ISSUE THREAD

**Issue by mberg** [SEL-Columbia/bamboo#350] opened 2012-12-28 12:11 UTC
This erases the data set!

``` shell
curl -X POST -F csv_file=@/home/mberg/Documents/bamboo-examples/data/water_points.csv http://bamboo.io/datasets

curl -X POST -d "name=protected_waterpoint&formula=water_source_type in [\"borehole\"]" http://bamboo.io/calculations/d997e6877f8a4d65b5eae6a3995c6773
```

**Comment by mberg** [comment] 2012-12-28 12:13
This is what calculations show.

[
{
formula: "water_source_type in ["borehole"]",
state: "pending",
group: null,
name: "protected_waterpoint"
}
]

**Comment by mberg** [comment] 2012-12-28 12:16
This too:

curl -X POST -d "name=big_poppa&formula=community_pop>5000" http://bamboo.io/calculations/ef6995b3b2894e969248122ac586613a

**Comment by pld** [comment] 2012-12-29 01:05
This is related to the format of the dataset that is uploaded.  The water_points.csv has duplicate column names (at least the one in the github repo) and pandas does not like this.

For the time being #354 will silently fail but not delete the dataset, an improvement.  I'm going to add an issue for uniquifying columns on upload.

**Comment by pld** [comment] 2012-12-29 01:13
Closing, since the deletion issue is fixed.  But still any operations on datasets with duplicate column names will result in unexpected behavior, issue for this is #355.

**Closed as completed by pld** 2012-12-29 01:13 UTC
Labels: error, priority
